### ISSUE TITLE
更新後に発生したERRORについての報告

### ISSUE THREAD

**Issue by 163g** [raspi0124/Japanese-font-for-TinyMCE#2]
いつも素晴らしいプラグインをありがとうございます。
おかげさまでWEBサイト構築が大変スムーズに行えており助かっています。

さて、今回はプラグインを最新に更新後Errorが出たので報告します。

＜発生状況＞
１．Japanese-font-for-TinyMCEのみ更新しました（他のテーマ・プラグインは更新せず）
２．更新後にError500が出たので、FTPからJapanese-font-for-TinyMCEを削除し復旧しました
また、他のプラグインやテーマはいずれも最新です

報告すべき項目がわからないのですが現在の環境の要点をお伝えします

・WPのバージョン：4.9.6–ja
・Japanese-font-for-TinyMCE：バージョン: 3.8
・仕様しているテーマ：Sydney Pro バージョン:1.57

更新以前は問題なく使用できていたので、大変恐縮ではありますがもし可能ならダウングレード版をご案内いただければ幸いです。

**Comment by 163g** [comment]
すいません。githubの使用方法を知らなかったので、見当違いなコメントをしてしまいました。
過去のバージョンにアクセスできることに今気づき、ダウングレードしてインストール致しました。
上記環境で「バージョン 3.7」で安定動作しております。

いつもありがとうございます。ご報告まで。

**Comment by raspi0124** [comment]
<a href="https://raspi-diary.com/post-1820/" rel="noopener" target="_blank">https://raspi-diary.com/post-1820/</a>
の方で解決法を公開しておりますのでよろしければご覧ください。
今回はご迷惑おかけしてすみませんでした。
(修正版をgithubに載せるのをわすれていました。。

**Comment by raspi0124** [comment]
追加でGithubにもアップロードしておきました。
