### ISSUE TITLE
Many Users meet 'Internal Server Error 500' or error statements on dashboard.

### ISSUE THREAD

**Issue by ttakao** [raspi0124/Japanese-font-for-TinyMCE#3]
My customers get many issues, such as internal server error 500 and dashboard error.
When removing this plugin, issues has gone.
Now I can not recommend to use this plugin. Particularly, server error 500 is hard to investigate for Wordpress users.

**Comment by raspi0124** [comment]
OK, Sorry for that issue.
It was my fault to use gutenberg's function without noticing it.
Now the fixed version is releaced but it looks too late..
Thanks for using the plugin! 
Additional information can be found here:
https://raspi-diary.com/post-1820/ (Japanese)
or you may look at google traslated version as you prefer using following link.
https://translate.google.com/translate?hl=ja&sl=ja&tl=en&u=https%3A%2F%2Fraspi-diary.com%2Fpost-1820%2F
